/*------------------------------------------------------------
 Create Dimensions Tables
------------------------------------------------------------*/

--------------------------------------------------------------
-- 1. Date Dimension
--------------------------------------------------------------
CREATE TABLE warehouse.dim_date (

    date_key INTEGER PRIMARY KEY,

    full_date DATE NOT NULL UNIQUE,

    day_number INTEGER NOT NULL,

    month_number INTEGER NOT NULL,

    month_name VARCHAR(20) NOT NULL,

    quarter_number INTEGER NOT NULL,

    year_number INTEGER NOT NULL,

    day_name VARCHAR(20) NOT NULL,

    week_number INTEGER NOT NULL,

    is_weekend BOOLEAN NOT NULL

);

--------------------------------------------------------------
-- 2. Category Dimension
--------------------------------------------------------------
CREATE TABLE warehouse.dim_category (

    category_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    category_id INTEGER UNIQUE NOT NULL,

    category_name VARCHAR(100),

    category_description TEXT,

    is_active BOOLEAN,

    created_at TIMESTAMP,

    updated_at TIMESTAMP

);


--------------------------------------------------------------
-- 3. Seller Dimension
--------------------------------------------------------------
CREATE TABLE warehouse.dim_seller (

    seller_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    seller_id INTEGER UNIQUE NOT NULL,

    seller_name VARCHAR(100),

    seller_business_name VARCHAR(100),

    seller_state VARCHAR(100),

    seller_city VARCHAR(100),

    seller_email VARCHAR(100),

    seller_phone VARCHAR(20),

    seller_rating NUMERIC(2,1),

    is_active BOOLEAN

);


--------------------------------------------------------------
-- 4. Customer Dimension
--------------------------------------------------------------
CREATE TABLE warehouse.dim_customer (

    customer_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_id INTEGER UNIQUE NOT NULL,

    customer_first_name VARCHAR(100),

    customer_last_name VARCHAR(100),

    customer_email VARCHAR(100),

    customer_phone VARCHAR(20),

    is_prime_member BOOLEAN

);

--------------------------------------------------------------
-- 5. Product Dimension
--------------------------------------------------------------
CREATE TABLE warehouse.dim_product (

    product_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id INTEGER UNIQUE NOT NULL,

    category_key INTEGER
        REFERENCES warehouse.dim_category(category_key),

    sku VARCHAR(100),

    product_name VARCHAR(200),

    brand_name VARCHAR(100),

    product_description TEXT,

    product_size VARCHAR(50),

    product_color VARCHAR(50),

    selling_price NUMERIC(10,2),

    cost_price NUMERIC(10,2),

    weight_grams NUMERIC(10,2),

    length_cm NUMERIC(10,2),

    width_cm NUMERIC(10,2),

    height_cm NUMERIC(10,2)
);