/*------------------------------------------------------------
 Create Facts Tables
------------------------------------------------------------*/

--------------------------------------------------------------
-- 1. Ssales Facts Table
--------------------------------------------------------------
CREATE TABLE warehouse.fact_sales (

    sales_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id INTEGER,

    order_item_id INTEGER,

    date_key INTEGER,

    customer_key INTEGER,

    seller_key INTEGER,

    product_key INTEGER,

    quantity INTEGER,

    selling_price NUMERIC(10,2),

    total_amount NUMERIC(10,2)

);


--------------------------------------------------------------
-- 2. Payment Facts Table
--------------------------------------------------------------
CREATE TABLE warehouse.fact_payments (

    payment_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    payment_id INTEGER,

    order_id INTEGER,

    customer_key INTEGER,

    date_key INTEGER,

    payment_method VARCHAR(30),

    payment_status VARCHAR(30),

    payment_amount NUMERIC(10,2)

);


--------------------------------------------------------------
-- 3. Returns Facts Table
--------------------------------------------------------------
CREATE TABLE warehouse.fact_returns (

    return_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    return_id INTEGER,

    order_id INTEGER,

    customer_key INTEGER,

    date_key INTEGER,

    return_reason VARCHAR(200),

    return_status VARCHAR(50)

);

--------------------------------------------------------------
-- 4. Reviews Facts Table
--------------------------------------------------------------
CREATE TABLE warehouse.fact_reviews (

    review_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    review_id INTEGER,

    order_id INTEGER,

    customer_key INTEGER,

    product_key INTEGER,

    date_key INTEGER,

    rating INTEGER

);